"""One-shot migration of the original single-book layout to the corpus layout.

    python tools/migrate_v1_to_v2.py <book_id> <old_ocr_cache_dir> [--old-root DIR]

v1 kept OCR at Pipeline/ocr_cache/<book>/sNNN{a,b}.json and put every sidecar at
Pipeline/ root, keyed by the book-local page id. v2 files everything under
Pipeline/books/<book_id>/ and keys on the globally unique page_id.

Page identity is remapped, not reinterpreted:

    s001a -> brihat-jataka/p0001      seq = (sheet - 1) * 2 + (1 if half a else 2)
    s001b -> brihat-jataka/p0002
    s115b -> brihat-jataka/p0230

The old sheet/half is preserved in `source_ref`, where it is provenance rather than
identity. Sidecar line indices are carried across unchanged -- the line payload is
byte-for-byte the same -- and are now bound to the OCR fingerprint.

The hallucination drop-list is deliberately NOT migrated: it is derived from the page
images and is regenerated by tools/calibrate_ink.py, which also records the calibration
that the migrated file could not have carried.
"""
import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout.reconfigure(encoding="utf-8")

from corpuslib import ir
from corpuslib.ids import local_name, page_id

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OLD_PAGE = re.compile(r"^s(\d{3})([ab])$")


def old_to_seq(name):
    m = OLD_PAGE.match(name)
    if not m:
        raise SystemExit(f"unrecognised v1 page name {name!r}")
    sheet, half = int(m.group(1)), m.group(2)
    return (sheet - 1) * 2 + (1 if half == "a" else 2), sheet, half


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("book_id")
    ap.add_argument("old_ocr")
    ap.add_argument("--old-root", default=ROOT)
    a = ap.parse_args()
    book_id, old_root = a.book_id, a.old_root

    # ---- 1. OCR -> IR ------------------------------------------------------------
    names = sorted(f[:-5] for f in os.listdir(a.old_ocr) if f.endswith(".json"))
    mapping, fps = {}, {}
    producer = {
        "name": "surya", "version": "0.14.7", "task": "ocr_with_boxes",
        "note": "migrated from the v1 cache; the original bulk_ocr.py recorded no run "
                "metadata, so device/date/dpi are unknown for these pages",
    }
    for name in names:
        seq, sheet, half = old_to_seq(name)
        lines = json.load(open(os.path.join(a.old_ocr, name + ".json"), encoding="utf-8"))
        pid = ir.write_page(ROOT, book_id, seq, lines,
                            {"pdf_page": sheet, "half": half, "v1_page": name},
                            producer)
        mapping[name] = pid
        fps[pid] = ir.fingerprint(lines)
    print(f"1. OCR -> IR              : {len(mapping)} pages "
          f"({names[0]} -> {mapping[names[0]]} .. {names[-1]} -> {mapping[names[-1]]})")

    bdir = ir.book_dir(ROOT, book_id)
    os.makedirs(bdir, exist_ok=True)

    # ---- 2. corrections ----------------------------------------------------------
    src = os.path.join(old_root, "corrections.json")
    if os.path.exists(src):
        old = json.load(open(src, encoding="utf-8"))
        new = []
        for c in old:
            pid = mapping[c["page"]]
            new.append({
                "page_id": pid, "ocr_fingerprint": fps[pid],
                "find": c["find"], "replace": c["replace"], "expect": c["expect"],
                "reason": c["reason"], "verified": c.get("verified", ""),
                "v1_page": c["page"],
            })
        json.dump({"schema": 2, "book_id": book_id, "corrections": new},
                  open(os.path.join(bdir, "corrections.json"), "w", encoding="utf-8"),
                  ensure_ascii=False, indent=1)
        print(f"2. corrections            : {len(new)} migrated")

    # ---- 3. page roles -----------------------------------------------------------
    src = os.path.join(old_root, "page_roles.json")
    if os.path.exists(src):
        old = json.load(open(src, encoding="utf-8"))
        excl = {}
        for name, reason in old.get("exclude", {}).items():
            pid = mapping[name]
            excl[pid] = {"ocr_fingerprint": fps[pid], "reason": reason,
                         "v1_page": name}
        doc = {"schema": 2, "book_id": book_id,
               "_comment": old.get("_comment", ""),
               "exclude": excl, "keep_note": old.get("keep_note", {})}
        json.dump(doc, open(os.path.join(bdir, "page_roles.json"), "w",
                            encoding="utf-8"), ensure_ascii=False, indent=1)
        print(f"3. page roles             : {len(excl)} exclusions migrated")

    # ---- 4. verified figures -----------------------------------------------------
    srcd = os.path.join(old_root, "verified")
    if os.path.isdir(srcd):
        dstd = os.path.join(bdir, "verified")
        os.makedirs(dstd, exist_ok=True)
        n = 0
        for fn in sorted(os.listdir(srcd)):
            if not fn.endswith(".json"):
                continue
            spec = json.load(open(os.path.join(srcd, fn), encoding="utf-8"))
            pid = mapping[spec["page"]]
            spec = dict(spec)
            spec.pop("page", None)
            spec = {"schema": 2, "page_id": pid, "ocr_fingerprint": fps[pid],
                    "v1_page": fn[:-5], **spec}
            json.dump(spec, open(os.path.join(dstd, local_name(pid) + ".json"), "w",
                                 encoding="utf-8"), ensure_ascii=False, indent=1)
            n += 1
        print(f"4. verified figures       : {n} migrated")

    json.dump({"book_id": book_id, "v1_to_v2": mapping},
              open(os.path.join(bdir, "migration_map.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)
    print(f"5. migration map written  : {os.path.join(bdir, 'migration_map.json')}")
    print("\nNOTE: ink_report.json is NOT migrated -- it derives from the page images. "
          "Run tools/calibrate_ink.py to regenerate it with a recorded calibration.")


if __name__ == "__main__":
    main()
