"""Regression suite for the vertical slice.

Run:  python -m pytest Engine/tests -q
"""

from __future__ import annotations

import json
import sys
from dataclasses import replace
from pathlib import Path

import pytest

from Engine.activate import activate, verify_claims
from Engine.chart import (
    BirthDataError,
    BirthRecord,
    compute_chart,
    resolve_birth,
)
from Engine.ephemeris import SwissEphemerisDLL
from Engine.facts import extract_facts, make_fact
from Engine.pipeline import PipelineError, run
from Engine.rules import evaluate, load_cards, verify_cards
from Engine.facts import FactSet

ROOT = Path(__file__).resolve().parents[2]
RULES = ROOT / "Rules"
CORPUS = ROOT / "Knowledge"

DEMO = BirthRecord(
    date="1987-03-14", time="04:22", timezone="Asia/Kolkata",
    latitude=10.7870, longitude=79.1378, place_name="Thanjavur",
    time_precision="minute", time_source="certificate",
)


@pytest.fixture(scope="module")
def provider():
    p = SwissEphemerisDLL()
    yield p
    p.close()


@pytest.fixture(scope="module")
def cards():
    return load_cards(RULES)


# --- golden ephemeris -------------------------------------------------------

# Astrodienst printed tables, Ephemeris/ae_2000d.pdf page 2, 1 January 2000
# 00:00 UT, tropical geocentric, truncated to whole arcminutes.
#
# Caveat worth stating: those tables are themselves generated by the Swiss
# Ephemeris (from JPL DE441). This check is therefore independent of our code
# path -- adapter, flags, ayanamsa handling, unit conversion -- but NOT
# independent of the underlying library. A genuinely independent oracle is
# still owed.
PRINTED_2000_01_01 = {
    "Sun":     270 + 9 + 51.55 / 60,
    "Moon":    210 + 7 + 18 / 60,
    "Mercury": 270 + 1 + 7 / 60,
    "Venus":   240 + 0 + 58 / 60,
    "Mars":    300 + 27 + 35 / 60,
    "Jupiter":   0 + 25 + 14 / 60,
    "Saturn":   30 + 10 + 24 / 60,
    "Rahu":    120 + 3 + 59 / 60,
}


@pytest.mark.parametrize("body,printed", sorted(PRINTED_2000_01_01.items()))
def test_matches_printed_ephemeris(provider, body, printed):
    jd = provider.julian_day_ut(2000, 1, 1, 0.0)
    ayanamsa = provider.ayanamsa(jd, "lahiri")
    tropical = (provider.body_position(jd, body, "lahiri").lon + ayanamsa) % 360.0
    arcmin = abs(((tropical - printed + 180.0) % 360.0) - 180.0) * 60.0
    assert arcmin < 1.0, f"{body}: {arcmin:.2f} arcmin from the printed table"


def test_ketu_is_exactly_opposite_rahu(provider):
    jd = provider.julian_day_ut(2000, 1, 1, 0.0)
    rahu = provider.body_position(jd, "Rahu", "lahiri").lon
    ketu = provider.body_position(jd, "Ketu", "lahiri").lon
    assert abs(((ketu - rahu) % 360.0) - 180.0) < 1e-9


def test_high_latitude_cusp_systems_refuse_rather_than_lie(provider):
    from Engine.ephemeris import EphemerisError
    jd = provider.julian_day_ut(2000, 1, 1, 0.0)
    provider.houses(jd, 78.0, 15.0, "whole_sign", "lahiri")   # always defined
    with pytest.raises(EphemerisError):
        provider.houses(jd, 78.0, 15.0, "placidus", "lahiri")


# --- birth data -------------------------------------------------------------

def test_dst_fall_back_is_an_error_not_a_guess(provider):
    # 2021-11-07 01:30 America/New_York happens twice.
    rec = BirthRecord(date="2021-11-07", time="01:30", timezone="America/New_York",
                      latitude=40.7, longitude=-74.0)
    with pytest.raises(BirthDataError, match="occurs twice"):
        resolve_birth(rec, provider)


def test_dst_spring_forward_gap_is_an_error(provider):
    # 2021-03-14 02:30 America/New_York never happened.
    rec = BirthRecord(date="2021-03-14", time="02:30", timezone="America/New_York",
                      latitude=40.7, longitude=-74.0)
    with pytest.raises(BirthDataError, match="does not exist"):
        resolve_birth(rec, provider)


def test_unknown_timezone_is_rejected(provider):
    rec = BirthRecord(date="2000-01-01", time="12:00", timezone="Mars/Olympus",
                      latitude=0.0, longitude=0.0)
    with pytest.raises(BirthDataError, match="unknown IANA"):
        resolve_birth(rec, provider)


def test_historical_offset_comes_from_tzdata(provider):
    # India ran +05:30 in 1987; the offset must be derived, not assumed.
    resolved = resolve_birth(DEMO, provider)
    assert resolved.utc_offset == "+05:30"
    assert resolved.offset_source == "zoneinfo/Asia/Kolkata"
    assert resolved.utc_instant == "1987-03-13T22:52:00Z"


def test_low_precision_time_raises_a_warning(provider):
    rec = BirthRecord(date="1987-03-14", time="04:00", timezone="Asia/Kolkata",
                      latitude=10.787, longitude=79.1378, time_precision="hour")
    assert any("precision" in w for w in resolve_birth(rec, provider).warnings)


# --- chart ------------------------------------------------------------------

def test_whole_sign_houses_count_from_the_lagna_sign(provider):
    chart = compute_chart(resolve_birth(DEMO, provider), provider)
    asc = chart.ascendant_sign_index
    for b in chart.bodies.values():
        assert b.house == ((b.sign_index - asc) % 12) + 1
    assert chart.bodies["Venus"].house == 1     # Venus shares the lagna sign


def test_bundle_id_changes_with_settings(provider):
    resolved = resolve_birth(DEMO, provider)
    a = compute_chart(resolved, provider, ayanamsa="lahiri")
    b = compute_chart(resolved, provider, ayanamsa="raman")
    assert a.bundle_id != b.bundle_id


def test_bundle_id_is_stable(provider):
    resolved = resolve_birth(DEMO, provider)
    a = compute_chart(resolved, provider)
    b = compute_chart(resolved, provider)
    assert a.bundle_id == b.bundle_id


def test_invariants_are_actually_checked(provider):
    chart = compute_chart(resolve_birth(DEMO, provider), provider)
    assert "nodes_opposed_180" in chart.invariants_checked
    assert "sun_moon_never_retrograde" in chart.invariants_checked


# --- rule store -------------------------------------------------------------

def test_every_card_quote_is_byte_exact_in_the_corpus(cards):
    assert cards, "no cards loaded"
    assert verify_cards(cards, CORPUS) == []


def test_chapter_eight_is_complete(cards):
    """9 bodies x 12 houses, with one deliberate exception.

    PD.08.Saturn.01 was split during verification (2026-08-24) into
    PD.08.Saturn.01.OwnOrExalted and .OtherSign: the quote itself states two
    mutually exclusive outcomes conditioned on Saturn's dignity in the Lagna,
    which a single in_house-only condition could not distinguish. So chapter 8
    has 109 cards over 108 distinct (subject, house) pairs, and exactly one
    pair -- Saturn in house 1 -- is covered by two dignity-discriminated cards
    instead of one.
    """
    ch8 = [c for c in cards if c.chapter == 8]
    assert len(ch8) == 109
    seen = {(c.predicts["subject"], c.predicts["house"]) for c in ch8}
    assert len(seen) == 108
    saturn_house1 = [c for c in ch8
                     if c.predicts["subject"] == "Saturn" and c.predicts["house"] == 1]
    assert {c.predicts.get("dignity") for c in saturn_house1} == {"own_or_exalted", "other"}


def test_chapter_nine_covers_every_ascendant(cards):
    lagna = [c for c in cards if c.chapter == 9 and c.predicts.get("subject") == "Ascendant"]
    assert len(lagna) == 12
    assert len({c.predicts["sign"] for c in lagna}) == 12


def test_inert_cards_declare_what_they_are_waiting_for(cards):
    """A card that cannot fire must say why, or the gap becomes invisible.

    Encoding knowledge ahead of the fact extractor is the intended order, but
    only while every such card is self-describing.
    """
    for c in cards:
        if c.raw.get("activation") == "inert":
            assert c.raw.get("requires"), f"{c.id} is inert but requires nothing"
            assert c.raw.get("note"), f"{c.id} is inert with no explanation"


def test_chapter_one_supplies_the_lordship_table(cards):
    """The table dep.lord-of-house will read, complete and one card per sign."""
    lords = {c.predicts["sign"]: c.predicts["graha"]
             for c in cards if c.predicts.get("relation") == "sign_lord"}
    assert len(lords) == 12
    assert lords["Aries"] == "Mars" and lords["Cancer"] == "Moon"
    assert lords["Leo"] == "Sun" and lords["Aquarius"] == "Saturn"
    # Every sign lord is one of the seven classical rulers, and each of the
    # five that rule two signs does so exactly twice.
    from collections import Counter
    counts = Counter(lords.values())
    assert counts["Sun"] == 1 and counts["Moon"] == 1
    assert all(counts[g] == 2 for g in ("Mars", "Mercury", "Jupiter",
                                        "Venus", "Saturn"))


def test_exaltation_and_debilitation_are_opposite(cards):
    """Chapter 1 states the principle; the table must obey it."""
    order = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra",
             "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"]
    rows = [c.predicts for c in cards
            if c.predicts.get("relation") == "exaltation"
            and "exaltation_sign" in c.predicts]
    assert len(rows) == 7
    for r in rows:
        i = order.index(r["exaltation_sign"])
        assert order[(i + 6) % 12] == r["debilitation_sign"], r


def test_chapter_two_supplies_the_natural_friendship_table(cards):
    """PD.02.Friendship.NaturalTable, recovered from PDF page 22 by matching
    each extracted line's bounding box to its column and row, then verified
    against a direct render of the printed page (2026-08-19). Reference
    doctrine, not a firing rule: dep.dignity-friendship has no extractor yet.

    Pinned to the exact printed table rather than to an assumed invariant
    such as symmetry -- the Sun/Mercury pair alone shows the table is not
    symmetric even apart from the Moon row's own defect, so any "reciprocal
    friendship" check would be this test inventing doctrine, not verifying it.
    """
    rows = [c for c in cards if c.id == "PD.02.Friendship.NaturalTable"]
    assert len(rows) == 1
    card = rows[0]
    assert card.activation == "reference"
    assert card.predicts["table"] == {
        "Sun":     {"friend": ["Moon", "Mars", "Jupiter"],
                    "neutral": ["Mercury"], "enemy": ["Venus", "Saturn"]},
        "Moon":    {"friend": ["Sun", "Mercury"],
                    "neutral": ["Mars", "Mercury", "Venus", "Saturn"],
                    "enemy": []},
        "Mars":    {"friend": ["Sun", "Moon", "Jupiter"],
                    "neutral": ["Venus", "Saturn"], "enemy": ["Mercury"]},
        "Mercury": {"friend": ["Sun", "Venus"],
                    "neutral": ["Mars", "Jupiter", "Saturn"],
                    "enemy": ["Moon"]},
        "Jupiter": {"friend": ["Sun", "Moon", "Mars"],
                    "neutral": ["Saturn"], "enemy": ["Mercury", "Venus"]},
        "Venus":   {"friend": ["Mercury", "Saturn"],
                    "neutral": ["Mars", "Jupiter"], "enemy": ["Sun", "Moon"]},
        "Saturn":  {"friend": ["Mercury", "Venus"],
                    "neutral": ["Jupiter"], "enemy": ["Sun", "Moon", "Mars"]},
    }
    # The one printed defect this table preserves rather than corrects.
    assert "Mercury" in card.predicts["table"]["Moon"]["friend"]
    assert "Mercury" in card.predicts["table"]["Moon"]["neutral"]


def test_chapter_six_supplies_the_pancha_mahapurusha_yogas(cards):
    """PD.06.Ruchaka/.Bhadra/.Hamsa/.Malavya/.Sasa -- verses 1-4, printed
    p.55-57. Each is a two-span card quoting its own naming clause (own sign
    or exaltation, in a kendra) and its own effect verse; the graha and its
    two dignities are exact per verses 1-5, never widened or guessed."""
    grahas = {"PD.06.Ruchaka": "Mars", "PD.06.Bhadra": "Mercury",
              "PD.06.Hamsa": "Jupiter", "PD.06.Malavya": "Venus",
              "PD.06.Sasa": "Saturn"}
    by_id = {c.id: c for c in cards if c.id in grahas}
    assert set(by_id) == set(grahas)
    for cid, graha in grahas.items():
        card = by_id[cid]
        assert card.activation == "active"
        assert len(card.spans) == 2, f"{cid} should quote condition and effect"
        assert card.predicts["yoga"] == cid.rsplit(".", 1)[-1]
        assert card.predicts["graha"] == graha
        leaf = card.conditions["all"][1]["in_house_class"]
        assert leaf == {"graha": graha, "klass": "kendra"}
        dignities = {d["dignity"]["dignity"] for d in card.conditions["all"][0]["any"]}
        assert dignities == {"own", "exalted"}


def test_chapter_six_citation_cards_are_reference_not_claims(cards):
    """Jataka Parijata's and Saravali's own restatements of the same five
    yogas are corroborating doctrine, not new predictive claims."""
    for cid in ("PD.06.PanchaMahapurusha.JatakaParijata",
                "PD.06.PanchaMahapurusha.Saravali"):
        card = next(c for c in cards if c.id == cid)
        assert card.activation == "reference"
        assert card.tier == 2
        assert card.conditions == {"all": []}


def test_golden_ruchaka_no_longer_fires_for_mars_in_own_sign_without_strength():
    """Mars sits in Aries, its own sign, in the 4th house -- a kendra -- in
    the golden chart, satisfying Ruchaka's own naming condition. Milestone 24
    added v.9's blanket strength requirement (passage:phaladeepika.06.p009) as
    an additional clause on all five Mahapurusha cards, and ch.4 vv.4-5's five
    verdict cards do not independently state "own sign => strong" -- only
    exaltation, retrogression (of the five non-luminaries), retrograde-in-
    debilitation and the nodes' own signs do. Mars here is not exalted and not
    retrograde, so no strength fact is emitted for it at all (neither strong
    nor weak), and Ruchaka -- along with the rest of the Mahapurusha family --
    now correctly withholds the claim. This is the real, evidenced consequence
    of the source's own additional gate, not a regression: the golden chart is
    the project's own negative control for it.
    """
    claims = {c.derived["rule_card"]: c for c in run(DEMO).claims
             if c.derived["rule_card"] in ("PD.06.Ruchaka", "PD.06.Bhadra",
                                           "PD.06.Hamsa", "PD.06.Malavya",
                                           "PD.06.Sasa")}
    assert set(claims) == set()


def test_golden_ruchaka_fires_once_mars_is_actually_vested_with_strength(provider, cards):
    """The positive control for the same finding: move Mars from Aries (own
    sign, no strength verdict) to Capricorn, its exaltation sign, keeping
    everything else on the golden chart exactly as the ephemeris produced it
    (the `place` convention established in test_strength.py -- edge cases here
    are placements, not fixtures). Capricorn is the golden chart's own 1st
    house (kendra) for this ascendant, so both of Ruchaka's own naming clauses
    (own-or-exalted dignity, kendra) and v.9's added strength clause are
    satisfied, and the claim returns.
    """
    from Engine.doctrine import Doctrine
    from Engine.tests.test_strength import place

    base = compute_chart(resolve_birth(DEMO, provider), provider)
    moved = place(base, "Mars", lon=280.0, retrograde=False)  # Capricorn
    assert moved.bodies["Mars"].sign == "Capricorn"
    assert moved.bodies["Mars"].house == 1

    doctrine = Doctrine.from_cards(cards)
    facts = extract_facts(moved, doctrine)
    claims, _ = activate(moved, facts, cards)
    fired = {c.derived["rule_card"] for c in claims}
    assert "PD.06.Ruchaka" in fired
    ruchaka = next(c for c in claims if c.derived["rule_card"] == "PD.06.Ruchaka")
    assert "strength(Mars,strong)" in ruchaka.derived["conditions_satisfied"]


def test_golden_adhama_and_sakata_fire_from_slice_three():
    """PD.06.Adhama (v.14-27 slice): the Moon in a kendra from the Sun.
    PD.06.Sakata: the Moon in the 6th from Jupiter, not cancelled here
    because the Moon is not in a kendra from the lagna in this chart."""
    r = run(DEMO)
    by_card = {c.derived["rule_card"]: c for c in r.claims
              if c.derived["rule_card"] in ("PD.06.Adhama", "PD.06.Sakata")}
    assert set(by_card) == {"PD.06.Adhama", "PD.06.Sakata"}
    assert "in_house_from(Moon,Sun,7)" in by_card["PD.06.Adhama"].derived["conditions_satisfied"]
    assert "in_house_from(Moon,Jupiter,6)" in by_card["PD.06.Sakata"].derived["conditions_satisfied"]
    assert r.verification.ok


def test_golden_kemadruma_does_not_fire_because_ketu_guards_the_moon():
    """PD.06.Kemadruma (v.5, slice 4): the golden chart's Moon is in Leo,
    house 8, with Ketu in Virgo -- the 2nd house from the Moon -- so the
    yoga's condition (no planet in the 2nd or 12th from the Moon) is false
    and the card must not fire. Confirms the card under-fires correctly
    rather than over-firing on an unrelated placement."""
    r = run(DEMO)
    ids = {c.derived["rule_card"] for c in r.claims}
    assert "PD.06.Kemadruma" not in ids
    assert "PD.06.Kemadruma.JatakaParijata1" not in ids
    assert r.verification.ok


def test_a_negation_only_trigger_renders_honestly_instead_of_empty():
    """A card satisfied entirely by absence (PD.06.Kemadruma) binds no
    variable, so conditions_satisfied is empty. The consultation trace must
    say so in words rather than print 'triggered by ' with nothing after it."""
    from Engine.render import _trigger_grounds

    assert _trigger_grounds([]) == (
        "a negative condition, satisfied by no graha in particular")
    assert _trigger_grounds(["in_house_from(Moon,Sun,7)"]) == (
        "`in_house_from(Moon,Sun,7)`")


def test_chapter_six_kemadruma_cards_do_not_assign_sunapha_anapha_durudhara(cards):
    """The naming ambiguity this slice exists to resolve (v.5 vs v.8's
    'respectively'): no card in the store may claim to know which of
    Sunapha, Anapha or Durudhara individually corresponds to a 2nd-only,
    12th-only, or both-occupied placement from the Moon. Only the yoga
    that verse 5 states unconditionally -- Kemadruma, their joint absence
    -- may be encoded from this passage."""
    ch06_yogas = {c.predicts.get("yoga") for c in cards
                  if c.book_id == "phaladeepika" and c.chapter == 6
                  and c.predicts.get("domain") == "yoga"}
    assert ch06_yogas.isdisjoint({"Sunapha", "Anapha", "Durudhara"})
    assert "Kemadruma" in ch06_yogas


def test_chapter_six_kemadruma_card_reads_absence_of_both_flanks(cards):
    card = next(c for c in cards if c.id == "PD.06.Kemadruma")
    assert card.activation == "active"
    assert len(card.spans) == 2
    assert card.predicts == {"domain": "yoga", "yoga": "Kemadruma"}
    leaf = card.conditions["all"][0]["not"]["any"]
    assert {"in_house_from": {"graha": "?p", "reference": "Moon", "house": 2}} in leaf
    assert {"in_house_from": {"graha": "?p", "reference": "Moon", "house": 12}} in leaf


def test_chapter_six_kemadruma_jataka_parijata_variant_is_moon_kendra_unaspected(cards):
    card = next(c for c in cards if c.id == "PD.06.Kemadruma.JatakaParijata1")
    assert card.activation == "active"
    assert card.predicts == {"domain": "yoga", "yoga": "Kemadruma",
                             "authority": "Jataka Parijata"}
    branches = card.conditions["any"]
    houses = {b["all"][0]["in_house"]["house"] for b in branches}
    assert houses == {1, 7}
    for b in branches:
        h = b["all"][0]["in_house"]["house"]
        assert b["all"][1] == {"not": {"aspects": {"graha": "Jupiter", "target": h}}}


def test_chapter_six_supplies_the_twelve_house_wise_yogas(cards):
    """PD.06.Chamara..Musala -- vv. 44-56, printed p.75-78. One repeating
    template: a benefic (?b) occupies or aspects the house; that house's own
    lord (?g) -- a distinct, independently-bound graha -- is not combust,
    sits in an auspicious house, in exaltation or own sign."""
    houses = {"Chamara": 1, "Dhenu": 2, "Shaurya": 3, "Jaladhi": 4,
              "Chhattra": 5, "Kama": 7, "Bhagya": 9, "Khyati": 10,
              "Parijata": 11, "Musala": 12}
    by_id = {c.id: c for c in cards if c.id in {f"PD.06.{n}" for n in houses}}
    assert set(by_id) == {f"PD.06.{n}" for n in houses}
    for name, house in houses.items():
        card = by_id[f"PD.06.{name}"]
        assert card.activation == "active"
        assert len(card.spans) == 1, f"{card.id} should be one contiguous span"
        assert card.predicts == {"domain": "yoga", "yoga": name, "house": house}
        leaves = card.conditions["all"]
        assert leaves[2]["lord_of_house"] == {"graha": "?g", "house": house}
        assert leaves[3] == {"not": {"combust": {"graha": "?g"}}}
        assert leaves[4]["in_house_class"] == {"graha": "?g", "klass": "auspicious"}
        occ = leaves[0]["any"]
        assert {"in_house": {"graha": "?b", "house": house}} in occ
        assert {"aspects": {"graha": "?b", "target": house}} in occ


def test_chapter_six_astra_is_printed_twice_and_stays_distinguishable(cards):
    """Astra Yoga names both the 6th-house and 8th-house member of the same
    family; the two cards must never collide."""
    h6 = next(c for c in cards if c.id == "PD.06.Astra.H06")
    h8 = next(c for c in cards if c.id == "PD.06.Astra.H08")
    assert h6.predicts == {"domain": "yoga", "yoga": "Astra", "house": 6}
    assert h8.predicts == {"domain": "yoga", "yoga": "Astra", "house": 8}
    assert h6.quote_sha256 != h8.quote_sha256
    notes = next(c for c in cards if c.id == "PD.06.Astra.H06.Notes")
    assert notes.activation == "reference"
    # Milestone 25 resolved this note's own forward reference to "Verse 57 of
    # this very chapter" by encoding vv.57-69; the note now names both cards
    # it corroborates.
    assert notes.raw["parallel_of"] == ["PD.06.Astra.H06", "PD.06.DusthanaLord.General"]


def test_golden_khyati_fires_with_two_independently_bound_grahas():
    """A real chart (2023-01-05, Pisces lagna): the Moon aspects the 10th
    house and is benefic; Jupiter, the 10th's own lord, sits in Sagittarius
    (his own sign) undisturbed -- ?b and ?g bind to different grahas."""
    rec = BirthRecord(date="2023-01-05", time="12:00", timezone="Asia/Kolkata",
                      latitude=10.7870, longitude=79.1378, place_name="Thanjavur",
                      time_precision="minute", time_source="certificate", sex="male")
    r = run(rec)
    claim = next(c for c in r.claims if c.derived["rule_card"] == "PD.06.Khyati")
    assert claim.derived["variables"] == {"?b": "Moon", "?g": "Jupiter"}
    assert r.verification.ok


def test_chapter_six_slice_three_inert_cards_never_fire(cards):
    """Vasumati (universal quantification) and Pushkala are recorded, not
    guessed at.

    Pushkala had three independent obstacles and dep.strength was only the
    first. Milestone 22 built that one, and the card stays inert on the other
    two -- an undefined compound-friendship tier ("the house of an Adhimitra")
    and an ambiguous reading ("together in a Kendra"). Its declared
    dependencies moved with it, which is the point of this assertion: a card
    that still cannot fire must not be left declaring a dependency that now
    exists, or the backlog reports it as released.
    """
    vasumati = next(c for c in cards if c.id == "PD.06.Vasumati")
    pushkala = next(c for c in cards if c.id == "PD.06.Pushkala")
    assert vasumati.activation == "inert"
    assert vasumati.raw["requires"] == ["dep.universal-quantification"]
    assert vasumati.conditions == {"all": []}
    assert pushkala.activation == "inert"
    assert pushkala.raw["requires"] == ["dep.compound-friendship",
                                        "dep.kendra-togetherness"]
    assert "dep.strength" not in pushkala.raw["requires"]
    assert pushkala.conditions == {"all": []}
    r = run(DEMO)
    fired = {c.derived["rule_card"] for c in r.claims}
    assert "PD.06.Vasumati" not in fired and "PD.06.Pushkala" not in fired


def test_chapter_six_adhama_sama_varishtha_have_distinct_quotes(cards):
    """One shared naming sentence (v. 18, \"respectively\"), three distinct
    effect fragments carved out of one shared effect sentence -- Varishtha's
    quote must not equal Sama's or Adhama's despite sharing a source paragraph."""
    by_id = {c.id: c for c in cards
             if c.id in ("PD.06.Varishtha", "PD.06.Sama", "PD.06.Adhama")}
    assert len(by_id) == 3
    shas = {c.quote_sha256 for c in by_id.values()}
    assert len(shas) == 3, "each yoga must have a distinct joined quote"
    assert by_id["PD.06.Varishtha"].quote_parts[0] == by_id["PD.06.Sama"].quote_parts[0]
    assert "Sama Yoga" in by_id["PD.06.Sama"].quote_parts[1]
    assert "Adhama Yoga" in by_id["PD.06.Adhama"].quote_parts[1]
    houses = {"PD.06.Adhama": (1, 4, 7, 10), "PD.06.Sama": (2, 5, 8, 11),
              "PD.06.Varishtha": (3, 6, 9, 12)}
    for cid, hs in houses.items():
        leaf = by_id[cid].conditions["all"][0]["any"]
        assert {h["in_house_from"]["house"] for h in leaf} == set(hs)


def test_chapter_six_subhamala_preserves_the_two_printed_spellings(cards):
    """\"Subnamala\" in the naming clause (v. 21) and \"Sumala\" in the effect
    verse (v. 22) are two different printed spellings, confirmed against the
    source page -- neither is corrected to match the other."""
    card = next(c for c in cards if c.id == "PD.06.Subhamala")
    assert "Subnamala" in card.quote_parts[0]
    assert "Sumala" in card.quote_parts[1]
    assert "Subhamala" not in card.quote


def test_golden_mahabhagya_fires_only_for_the_matching_sex():
    """A real chart (2023-01-11 09:00): Aquarius lagna, Sun in Sagittarius,
    Moon in Leo -- all odd signs -- and the Sun above the horizon. Mahabhagya
    for a male nativity, never for a female one at the same instant."""
    male = BirthRecord(date="2023-01-11", time="09:00", timezone="Asia/Kolkata",
                       latitude=10.7870, longitude=79.1378, place_name="Thanjavur",
                       time_precision="minute", time_source="certificate", sex="male")
    female = replace(male, sex="female")
    r_male = run(male)
    r_female = run(female)
    male_hits = [c.derived["rule_card"] for c in r_male.claims if "Mahabhagya" in c.derived["rule_card"]]
    female_hits = [c.derived["rule_card"] for c in r_female.claims if "Mahabhagya" in c.derived["rule_card"]]
    assert male_hits == ["PD.06.Mahabhagya.Male"]
    assert female_hits == []
    assert r_male.verification.ok and r_female.verification.ok


def test_reference_cards_never_become_claims():
    """A reference card carries a datum, not an assertion about a nativity."""
    r = run(DEMO)
    ref = {c.id for c in load_cards(RULES) if c.activation == "reference"}
    assert ref, "no reference cards in the store"
    for c in r.claims:
        assert c.derived["rule_card"] not in ref


def test_nothing_is_silently_deferred():
    """The deferred-knowledge registry must account for every gap.

    Three kinds of gap are found by machine, not by memory: inert cards read
    out of the store, paragraphs of an encoded chapter that no card quotes, and
    chapters the manifest does not declare extracted. Any one of them without
    a registry entry fails here.
    """
    sys.path.insert(0, str(ROOT / "Rules" / "tools"))
    from backlog import build as build_backlog

    entries, _, _, _, _, problems, _ = build_backlog()
    assert not problems, problems
    assert entries, "the backlog built empty, which means it is not looking"


def test_backlog_report_is_current(tmp_path):
    """Reports/PHASE3_BACKLOG.md is generated; a stale one is a lie."""
    sys.path.insert(0, str(ROOT / "Rules" / "tools"))
    import backlog

    entries, registry, state, resolvable, available, _, counts = backlog.build()
    fresh = backlog.render(registry, entries, state, resolvable,
                           available, counts) + "\n"
    on_disk = (ROOT / "Reports" / "PHASE3_BACKLOG.md").read_text(encoding="utf-8")
    assert fresh == on_disk, (
        "Reports/PHASE3_BACKLOG.md is out of date; "
        "run: python Rules/tools/backlog.py --write")


def test_the_plan_does_not_charge_for_chapters_already_encoded():
    """A capability's chapter dependency stays listed after the chapter is done.

    Counting those unconditionally made the work order charge for finished work:
    dep.nature was costed at 21 units when its code was 2 and chapter 2 had been
    encoded for days, which buried a cheap, highly-connected capability in a
    ranking whose only job is to surface one.
    """
    sys.path.insert(0, str(ROOT / "Rules" / "tools"))
    import leverage

    done = leverage.encoded_chapters()
    assert ("phaladeepika", 2) in done, "chapter 2 is encoded per the manifest"
    assert ("phaladeepika", 7) not in done, "chapter 7 is not yet encoded per the manifest"

    deps = json.loads((RULES / "deferred.json").read_text(encoding="utf-8"))["dependencies"]
    fake = {"dep.x": {"depends_on": ["chapter:phaladeepika.02",
                                     "chapter:phaladeepika.07"]}}
    needed = leverage.chapters_needed({"dep.x"}, fake, done)
    assert needed == {"chapter:phaladeepika.07"}

    # And no capability in the real registry is still billed for an encoded one.
    for dep_id in deps:
        for ch in leverage.chapters_needed({dep_id}, deps, done):
            assert leverage.parse_chapter_dep(ch) not in done, (dep_id, ch)


def test_a_tampered_quote_is_detected(cards, tmp_path):
    """The verifier must catch a card that no longer matches the corpus."""
    doc = json.loads((RULES / "phaladeepika" / "ch08.json").read_text(encoding="utf-8"))
    doc["cards"][0]["source"]["quote"] += " and will win the lottery."
    d = tmp_path / "phaladeepika"
    d.mkdir()
    (d / "ch08.json").write_text(json.dumps(doc), encoding="utf-8")
    problems = verify_cards(load_cards(tmp_path), CORPUS)
    assert any("does not match corpus" in p for p in problems)


def test_a_shifted_span_is_detected(cards, tmp_path):
    doc = json.loads((RULES / "phaladeepika" / "ch08.json").read_text(encoding="utf-8"))
    s = doc["cards"][0]["source"]
    s["char_span"] = [s["char_span"][0] + 5, s["char_span"][1] + 5]
    d = tmp_path / "phaladeepika"
    d.mkdir()
    (d / "ch08.json").write_text(json.dumps(doc), encoding="utf-8")
    assert verify_cards(load_cards(tmp_path), CORPUS) != []


def test_pipeline_refuses_to_run_on_an_unverified_store(tmp_path):
    doc = json.loads((RULES / "phaladeepika" / "ch08.json").read_text(encoding="utf-8"))
    doc["cards"][0]["source"]["quote"] = "invented"
    d = tmp_path / "phaladeepika"
    d.mkdir()
    (d / "ch08.json").write_text(json.dumps(doc), encoding="utf-8")
    with pytest.raises(PipelineError, match="failed verification"):
        run(DEMO, rules_dir=tmp_path, corpus_dir=CORPUS)


# --- condition evaluator ----------------------------------------------------

def _facts(*pairs):
    frame = {"reference": "lagna", "varga": "D1", "house_system": "whole_sign"}
    return FactSet([make_fact("in_house", {"graha": g, "house": h}, frame)
                    for g, h in pairs])


def test_evaluator_matches_and_reports_bindings():
    ev = evaluate({"all": [{"in_house": {"graha": "Sun", "house": 10}}]},
                  _facts(("Sun", 10)))
    assert ev.satisfied and ev.bindings == ("in_house(Sun,10)",)


def test_evaluator_does_not_confuse_adjacent_houses():
    ev = evaluate({"all": [{"in_house": {"graha": "Mars", "house": 7}}]},
                  _facts(("Mars", 8)))
    assert not ev.satisfied


def test_all_requires_every_condition():
    cond = {"all": [{"in_house": {"graha": "Sun", "house": 10}},
                    {"in_house": {"graha": "Moon", "house": 4}}]}
    assert not evaluate(cond, _facts(("Sun", 10))).satisfied
    assert evaluate(cond, _facts(("Sun", 10), ("Moon", 4))).satisfied


def test_unknown_predicate_is_inert_never_true():
    ev = evaluate({"all": [{"exalted": {"graha": "Sun"}}]}, _facts(("Sun", 10)))
    assert not ev.satisfied and ev.missing == ("exalted",)


# --- end to end -------------------------------------------------------------

def test_slice_runs_and_verifies():
    r = run(DEMO)
    assert r.verification.ok
    # Nine bodies each matching a placement card, one keyed on the ascendant's
    # sign, and twenty-two from quantified cards: two on the lagna, three on
    # dignity and combustion, five released by benefic/malefic nature -- three
    # of them one card naming each malefic that afflicts the 7th lord in turn
    # -- one from the Moon-sign transfer (dep.rule-transfer), eight from
    # dep.dignity-friendship (three grahas classed friend, one neutral, and
    # four solutions of PD.10.WifeDeprived.Lord7Afflicted's own quantified
    # "any": three inimical, one combust), Adhama Yoga (the Moon in a kendra
    # from the Sun), and Sakata Yoga (the Moon in the 6th from Jupiter, not
    # cancelled here); plus two from chapter 6 slice 7's dispositor-chain
    # yogas (v.35-36), both released by the same underlying fact -- Saturn
    # (the lagna lord) sits in the 11th, whose lord Mars sits in the 4th (a
    # kendra) in Mars's own sign, the same placement Ruchaka's naming clause
    # tests: Parvata Yoga (Mars, ?g2, tested directly) and Kahala Yoga -- the
    # dispositor one, PD.06.Kahala.Dispositor, distinct from the Parivartana
    # PD.06.Kahala of v.32-34 -- which takes the one further hop and finds
    # Mars is its own dispositor there, so ?g3 is Mars again; plus one more
    # from chapter 6 slice 8's Shankha Yoga (v.37): Venus lords both the
    # 10th (a kendra, Libra) and the 5th (a trikona, Taurus) on this chart
    # and sits in the 1st (an auspicious house), satisfying PD.06.Shankha
    # with the same graha filling both the kendra-lord and trikona-lord
    # roles. PD.06.RajaYoga does not fire here -- the 9th and 10th lords
    # are not together. Ruchaka Yoga itself does NOT fire on this chart (see
    # below) even though Mars sits in Aries, its own sign, in the 4th: that
    # placement satisfies the yoga's own naming clause but not v.9's added
    # strength clause. This number tracks the rule store: it must change
    # when doctrine is added, and never on its own.
    #
    # 40 -> 59 in Milestone 25: nineteen new claims from the vv.57-69
    # dusthana-lord-yoga family (PD.06.DusthanaLord.*), all off the template's
    # own quantified "any" (PD.06.DusthanaLord.General) -- a dusthana lord in
    # the house, or a malefic occupying or aspecting it, each satisfying
    # binding its own claim. One each for Ava (Saturn aspects 1), Duryoga
    # (Mars aspects 10), Dushkriti (Mars aspects 7), Kuhu (Mars occupies 4)
    # and Pamara (Saturn aspects 5); two each for Daridrya (Mars aspects 11;
    # Saturn occupies 11) and Nirbhagya (Rahu aspects 9; Ketu occupies 9);
    # three each for Mriti (Ketu aspects 3; Jupiter, lord of 12, sits in 3;
    # Rahu occupies 3) and Sarala (Sun, Mercury and Saturn each independently
    # aspect 8); four for Nisswa (Sun, lord of 8, sits in 2; Sun also occupies
    # 2 as a malefic; Mercury, lord of 6, sits in 2; Mercury also occupies 2
    # as a malefic). None of the ten new Parashara cards fire here: each needs
    # one *specific* dusthana lord in one *specific* dusthana, and this
    # chart's two dusthana-lord solutions above (Nisswa's Sun/Mercury, Mriti's
    # Jupiter) land in houses 2 and 3, neither a dusthana -- see
    # test_adjudication.py's demo-chart adjudications, all `recorded` rather
    # than `unresolved` for exactly this reason. A real chart for the genuine
    # chart-dependent Mantreswara/Parashara contradiction is exercised
    # separately (Milestone 25's own dedicated fixture, not the demo chart).
    #
    # 41 -> 40 in Milestone 24: PD.06.Ruchaka stopped firing on this chart.
    # v.9's blanket strength condition (passage:phaladeepika.06.p009) was
    # added to all five Pancha Mahapurusha cards; ch.4 vv.4-5's verdict cards
    # do not independently state "own sign => strong" (only exaltation,
    # retrogression, retrograde-in-debilitation and the nodes' own signs do),
    # so Mars here -- own sign, not exalted, not retrograde -- gets no
    # strength fact at all, and Ruchaka correctly withholds the claim. See
    # test_golden_ruchaka_no_longer_fires_for_mars_in_own_sign_without_strength
    # and its positive-control sibling above. Nothing else on this chart moved.
    #
    # 35 -> 41 in Milestone 20, when BJ.02.Nature.Benefics supplied the
    # natural-benefic classification of Jupiter and Venus that no encoded
    # card had previously carried. Five further cards reach their conditions
    # on this chart as a direct result -- PD.06.Parijata, PD.06.Subhavesi,
    # PD.06.Subhavasi, PD.06.Subhobhayachari and PD.10.Couple.BeneficAspect,
    # every one of them a rule about benefics that could not fire while the
    # two principal benefics were unclassified. Nothing that fired before
    # stopped firing: the change is purely additive, which is what adding a
    # classification (rather than altering one) should do.
    assert r.verification.checks["claims"] == 59
    for k in ("quote_integrity_passed", "conditions_reevaluated_passed",
              "numeric_grounding_passed"):
        assert r.verification.checks[k] == 59


def test_every_claim_has_all_four_provenance_links():
    for c in run(DEMO).claims:
        assert c.astronomical["quantities"] and c.astronomical["bundle_id"]
        assert c.derived["rule_card"] and c.derived["conditions_satisfied"]
        assert c.source["book_title"] and c.source["chapter"]
        assert c.passage["quote"] and c.passage["char_span"] and c.passage["page_anchor"]


def test_every_sentence_is_sourced():
    r = run(DEMO)
    known = {c.claim_id for c in r.claims}
    assert r.sentences
    for s in r.sentences:
        assert s.claim_ids and set(s.claim_ids) <= known


def test_quoted_output_adds_no_words():
    """The Part 2 composer quotes; it must not paraphrase."""
    r = run(DEMO)
    by_id = {c.claim_id: c for c in r.claims}
    rules = [s for s in r.sentences if s.part == "rules"]
    assert len(rules) == 59  # see test_slice_runs_and_verifies for the 40 -> 59 move
    for s in rules:
        assert s.text == by_id[s.claim_ids[0]].passage["quote_display"]


def test_coverage_reports_silence(provider):
    """A chart whose bodies have no cards must say so rather than invent."""
    chart = compute_chart(resolve_birth(DEMO, provider), provider)
    facts = extract_facts(chart)
    claims, report = activate(chart, facts, [], {})
    assert claims == [] and report["claims_activated"] == 0


def test_engine_names_no_book():
    """Extensibility guard (architecture 7.2).

    A book identifier anywhere in the engine means the corpus has leaked into
    the reasoning layer, and adding a book would then require an engine change.
    """
    banned = ("phaladeepika", "brihat-jataka", "mantreswara", "varahamihira")
    offenders = []
    for py in (ROOT / "Engine").rglob("*.py"):
        if "tests" in py.parts:
            continue
        low = py.read_text(encoding="utf-8").lower()
        for word in banned:
            if word in low:
                offenders.append(f"{py.relative_to(ROOT)}: {word}")
    assert not offenders, offenders


# --- the three-part consultation --------------------------------------------

def test_consultation_has_three_distinct_parts():
    text = run(DEMO).consultation
    for heading in ("## Part 1 — Objective chart facts",
                    "## Part 2 — Activated classical rules",
                    "## Part 3 — Synthesised interpretation"):
        assert heading in text, heading
    assert text.index("## Part 1") < text.index("## Part 2") < text.index("## Part 3")


def test_part_one_carries_no_citations():
    """Objective facts must not be mixed with doctrine."""
    text = run(DEMO).consultation
    part1 = text[text.index("## Part 1"):text.index("## Part 2")]
    assert "Phaladeepika" not in part1
    assert "PD.08" not in part1
    assert "printed p." not in part1


def test_part_two_cites_every_rule_to_the_page():
    r = run(DEMO)
    part2 = r.consultation[r.consultation.index("## Part 2"):
                           r.consultation.index("## Part 3")]
    for c in r.claims:
        assert c.claim_id in part2
        assert c.derived["rule_card"] in part2
        assert c.passage["page_anchor"] in part2
        assert c.passage["quote_display"] in part2


def test_an_ascendant_keyed_rule_reaches_the_report():
    """Regression: a claim with no house of its own was dropped from Part 2.

    Part 2 grouped claims by house, and a card keyed on `lagna_sign` has none.
    The claim was activated, verified and counted -- and then never rendered,
    so the report was silently missing a rule that had fired.
    """
    r = run(DEMO)
    lagna = [c for c in r.claims
             if not any(f["key"].startswith("in_house(")
                        for f in c.derived["facts"])]
    assert lagna, "no ascendant-keyed claim activated for the demo chart"
    part2 = r.consultation[r.consultation.index("## Part 2"):
                           r.consultation.index("## Part 3")]
    for c in lagna:
        assert c.claim_id in part2
        assert c.passage["quote_display"] in part2
    assert "### The Ascendant" in part2


def test_part_three_cites_only_claims_from_part_two():
    r = run(DEMO)
    known = {c.claim_id for c in r.claims}
    synth = [s for s in r.sentences if s.part == "synthesis"]
    assert synth, "synthesis produced nothing"
    for s in synth:
        assert set(s.claim_ids) <= known


# --- synthesis --------------------------------------------------------------

def _claim(cid, house, quote):
    from Engine.activate import Claim
    return Claim(
        claim_id=cid,
        astronomical={"bundle_id": "x", "settings": {}, "backend": "", "quantities": []},
        derived={"facts": [{"key": f"in_house(Sun,{house})", "frame": {}, "evidence": {}}],
                 "rule_card": "X", "conditions_satisfied": [f"in_house(Sun,{house})"]},
        source={"book_id": "b", "book_title": "B", "author": "", "translator": "",
                "chapter": 1, "verse": "1", "tier": 1},
        passage={"quote": quote, "quote_display": quote, "corpus_file": "",
                 "char_span": [0, 1], "quote_sha256": "", "page_anchor": None,
                 "span_trimmed": None},
        weight=1.0, specificity=1, tier=1, stability="stable", text=quote,
    )


def test_synthesis_detects_a_contested_term():
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "The native will be wealthy and strong."),
              _claim("clm-2", 2, "The native will be devoid of wealth.")]
    themes = {t.term: t for t in synthesise(claims).themes}
    assert "wealth" in themes
    assert themes["wealth"].contested
    assert themes["wealth"].asserted == ("clm-1",)
    assert themes["wealth"].negated == ("clm-2",)


def test_synthesis_reads_destroy_as_negation():
    """Regression: 'He will destroy his wealth' once read as asserting wealth."""
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "The native will be wealthy and strong."),
              _claim("clm-2", 2, "He will destroy his wealth and take to bad conduct.")]
    themes = {t.term: t for t in synthesise(claims).themes}
    assert themes["wealth"].negated == ("clm-2",)


def test_synthesis_ignores_terms_in_a_single_passage():
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "The native will be wealthy."),
              _claim("clm-2", 2, "The native will be learned.")]
    assert synthesise(claims).themes == ()


def test_synthesis_ignores_scaffolding_words():
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "Saturn makes the native strong at birth."),
              _claim("clm-2", 2, "Jupiter makes the native bold at birth.")]
    assert [t.term for t in synthesise(claims).themes] == []


def test_synthesis_verifier_catches_a_word_not_in_the_passage():
    from Engine.synthesis import Occurrence, Theme, SynthesisResult, verify_synthesis
    claims = [_claim("clm-1", 1, "The native will be wealthy.")]
    bogus = SynthesisResult(
        concentrations=(),
        themes=(Theme("elephant", ("elephant",),
                      (Occurrence("clm-1", "elephant", False, None),)),),
        method_note="", total_claims=1,
    )
    problems = verify_synthesis(bogus, claims)
    assert any("not in clm-1" in p for p in problems)


def test_synthesis_concentration_matches_the_chart():
    r = run(DEMO)
    for con in r.synthesis.concentrations:
        occupants = [b.body for b in r.chart.bodies.values() if b.house == con.house]
        assert sorted(con.bodies) == sorted(occupants)
        assert len(con.claim_ids) > 1


def test_verification_records_synthesis_checks():
    r = run(DEMO)
    assert r.verification.checks["synthesis_grounded"] is True
    assert r.verification.checks["sentences_all_sourced"] == len(r.sentences)


# --- determinism -------------------------------------------------------------

def test_method_note_is_stable_across_processes():
    """Regression: the note sliced NEGATION_CUES (a frozenset) before sorting.

    Set iteration order for strings varies per process, so the same chart
    rendered a different method note on every run. An in-process check cannot
    catch this -- the hash seed is fixed for the life of the interpreter -- so
    each sample must be a separate subprocess.
    """
    import subprocess
    code = (
        "from Engine.synthesis import synthesise;"
        "print(synthesise([]).method_note)"
    )
    notes = {
        subprocess.run([sys.executable, "-c", code], cwd=ROOT,
                       capture_output=True, text=True, check=True).stdout
        for _ in range(4)
    }
    assert len(notes) == 1, f"method note varies between runs: {notes}"


def test_consultation_is_byte_identical_across_processes():
    """The whole report must be reproducible, not just the parts we thought of."""
    import subprocess
    code = (
        "from Engine.chart import BirthRecord;"
        "from Engine.pipeline import run;"
        "r = run(BirthRecord(date='1987-03-14', time='04:22',"
        "  timezone='Asia/Kolkata', latitude=10.7870, longitude=79.1378,"
        "  place_name='Thanjavur', time_precision='minute',"
        "  time_source='certificate'));"
        "import hashlib;"
        "print(hashlib.sha256(r.consultation.encode('utf-8')).hexdigest())"
    )
    digests = {
        subprocess.run([sys.executable, "-c", code], cwd=ROOT,
                       capture_output=True, text=True, check=True).stdout.strip()
        for _ in range(3)
    }
    assert len(digests) == 1, f"consultation is not reproducible: {digests}"


def test_consultation_reports_cross_book_agreement_without_scoring_it():
    """Milestone 20: with two books in the store, agreement becomes visible.

    The relationship between authorities has to reach the reader, not just the
    evidence dict -- but as a count of books, never as a weight. The engine has
    no mechanism for preferring one authority to another and the consultation
    must not imply otherwise.
    """
    text = run(DEMO).consultation
    assert "**Cross-book agreement**" in text
    assert "stated independently by 2 books" in text
    assert "Agreement is reported, not scored." in text
    # A graha only one book classifies must be listed as such, not as agreed.
    assert "Resting on a single authority:" in text
    for banned in ("confidence", "score of", "weighted", "outranks"):
        assert banned not in text.lower(), banned
