"""Regression suite for the vertical slice.

Run:  python -m pytest Engine/tests -q
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from Engine.activate import activate, verify_claims
from Engine.chart import (
    BirthDataError,
    BirthRecord,
    compute_chart,
    resolve_birth,
)
from Engine.ephemeris import SwissEphemerisDLL
from Engine.facts import extract_facts, make_fact
from Engine.pipeline import PipelineError, run
from Engine.rules import evaluate, load_cards, verify_cards
from Engine.facts import FactSet

ROOT = Path(__file__).resolve().parents[2]
RULES = ROOT / "Rules"
CORPUS = ROOT / "Knowledge"

DEMO = BirthRecord(
    date="1987-03-14", time="04:22", timezone="Asia/Kolkata",
    latitude=10.7870, longitude=79.1378, place_name="Thanjavur",
    time_precision="minute", time_source="certificate",
)


@pytest.fixture(scope="module")
def provider():
    p = SwissEphemerisDLL()
    yield p
    p.close()


@pytest.fixture(scope="module")
def cards():
    return load_cards(RULES)


# --- golden ephemeris -------------------------------------------------------

# Astrodienst printed tables, Ephemeris/ae_2000d.pdf page 2, 1 January 2000
# 00:00 UT, tropical geocentric, truncated to whole arcminutes.
#
# Caveat worth stating: those tables are themselves generated by the Swiss
# Ephemeris (from JPL DE441). This check is therefore independent of our code
# path -- adapter, flags, ayanamsa handling, unit conversion -- but NOT
# independent of the underlying library. A genuinely independent oracle is
# still owed.
PRINTED_2000_01_01 = {
    "Sun":     270 + 9 + 51.55 / 60,
    "Moon":    210 + 7 + 18 / 60,
    "Mercury": 270 + 1 + 7 / 60,
    "Venus":   240 + 0 + 58 / 60,
    "Mars":    300 + 27 + 35 / 60,
    "Jupiter":   0 + 25 + 14 / 60,
    "Saturn":   30 + 10 + 24 / 60,
    "Rahu":    120 + 3 + 59 / 60,
}


@pytest.mark.parametrize("body,printed", sorted(PRINTED_2000_01_01.items()))
def test_matches_printed_ephemeris(provider, body, printed):
    jd = provider.julian_day_ut(2000, 1, 1, 0.0)
    ayanamsa = provider.ayanamsa(jd, "lahiri")
    tropical = (provider.body_position(jd, body, "lahiri").lon + ayanamsa) % 360.0
    arcmin = abs(((tropical - printed + 180.0) % 360.0) - 180.0) * 60.0
    assert arcmin < 1.0, f"{body}: {arcmin:.2f} arcmin from the printed table"


def test_ketu_is_exactly_opposite_rahu(provider):
    jd = provider.julian_day_ut(2000, 1, 1, 0.0)
    rahu = provider.body_position(jd, "Rahu", "lahiri").lon
    ketu = provider.body_position(jd, "Ketu", "lahiri").lon
    assert abs(((ketu - rahu) % 360.0) - 180.0) < 1e-9


def test_high_latitude_cusp_systems_refuse_rather_than_lie(provider):
    from Engine.ephemeris import EphemerisError
    jd = provider.julian_day_ut(2000, 1, 1, 0.0)
    provider.houses(jd, 78.0, 15.0, "whole_sign", "lahiri")   # always defined
    with pytest.raises(EphemerisError):
        provider.houses(jd, 78.0, 15.0, "placidus", "lahiri")


# --- birth data -------------------------------------------------------------

def test_dst_fall_back_is_an_error_not_a_guess(provider):
    # 2021-11-07 01:30 America/New_York happens twice.
    rec = BirthRecord(date="2021-11-07", time="01:30", timezone="America/New_York",
                      latitude=40.7, longitude=-74.0)
    with pytest.raises(BirthDataError, match="occurs twice"):
        resolve_birth(rec, provider)


def test_dst_spring_forward_gap_is_an_error(provider):
    # 2021-03-14 02:30 America/New_York never happened.
    rec = BirthRecord(date="2021-03-14", time="02:30", timezone="America/New_York",
                      latitude=40.7, longitude=-74.0)
    with pytest.raises(BirthDataError, match="does not exist"):
        resolve_birth(rec, provider)


def test_unknown_timezone_is_rejected(provider):
    rec = BirthRecord(date="2000-01-01", time="12:00", timezone="Mars/Olympus",
                      latitude=0.0, longitude=0.0)
    with pytest.raises(BirthDataError, match="unknown IANA"):
        resolve_birth(rec, provider)


def test_historical_offset_comes_from_tzdata(provider):
    # India ran +05:30 in 1987; the offset must be derived, not assumed.
    resolved = resolve_birth(DEMO, provider)
    assert resolved.utc_offset == "+05:30"
    assert resolved.offset_source == "zoneinfo/Asia/Kolkata"
    assert resolved.utc_instant == "1987-03-13T22:52:00Z"


def test_low_precision_time_raises_a_warning(provider):
    rec = BirthRecord(date="1987-03-14", time="04:00", timezone="Asia/Kolkata",
                      latitude=10.787, longitude=79.1378, time_precision="hour")
    assert any("precision" in w for w in resolve_birth(rec, provider).warnings)


# --- chart ------------------------------------------------------------------

def test_whole_sign_houses_count_from_the_lagna_sign(provider):
    chart = compute_chart(resolve_birth(DEMO, provider), provider)
    asc = chart.ascendant_sign_index
    for b in chart.bodies.values():
        assert b.house == ((b.sign_index - asc) % 12) + 1
    assert chart.bodies["Venus"].house == 1     # Venus shares the lagna sign


def test_bundle_id_changes_with_settings(provider):
    resolved = resolve_birth(DEMO, provider)
    a = compute_chart(resolved, provider, ayanamsa="lahiri")
    b = compute_chart(resolved, provider, ayanamsa="raman")
    assert a.bundle_id != b.bundle_id


def test_bundle_id_is_stable(provider):
    resolved = resolve_birth(DEMO, provider)
    a = compute_chart(resolved, provider)
    b = compute_chart(resolved, provider)
    assert a.bundle_id == b.bundle_id


def test_invariants_are_actually_checked(provider):
    chart = compute_chart(resolve_birth(DEMO, provider), provider)
    assert "nodes_opposed_180" in chart.invariants_checked
    assert "sun_moon_never_retrograde" in chart.invariants_checked


# --- rule store -------------------------------------------------------------

def test_every_card_quote_is_byte_exact_in_the_corpus(cards):
    assert cards, "no cards loaded"
    assert verify_cards(cards, CORPUS) == []


def test_chapter_eight_is_complete(cards):
    ch8 = [c for c in cards if c.chapter == 8]
    assert len(ch8) == 108           # 9 bodies x 12 houses
    seen = {(c.predicts["subject"], c.predicts["house"]) for c in ch8}
    assert len(seen) == 108


def test_a_tampered_quote_is_detected(cards, tmp_path):
    """The verifier must catch a card that no longer matches the corpus."""
    doc = json.loads((RULES / "phaladeepika" / "ch08.json").read_text(encoding="utf-8"))
    doc["cards"][0]["source"]["quote"] += " and will win the lottery."
    d = tmp_path / "phaladeepika"
    d.mkdir()
    (d / "ch08.json").write_text(json.dumps(doc), encoding="utf-8")
    problems = verify_cards(load_cards(tmp_path), CORPUS)
    assert any("does not match corpus" in p for p in problems)


def test_a_shifted_span_is_detected(cards, tmp_path):
    doc = json.loads((RULES / "phaladeepika" / "ch08.json").read_text(encoding="utf-8"))
    s = doc["cards"][0]["source"]
    s["char_span"] = [s["char_span"][0] + 5, s["char_span"][1] + 5]
    d = tmp_path / "phaladeepika"
    d.mkdir()
    (d / "ch08.json").write_text(json.dumps(doc), encoding="utf-8")
    assert verify_cards(load_cards(tmp_path), CORPUS) != []


def test_pipeline_refuses_to_run_on_an_unverified_store(tmp_path):
    doc = json.loads((RULES / "phaladeepika" / "ch08.json").read_text(encoding="utf-8"))
    doc["cards"][0]["source"]["quote"] = "invented"
    d = tmp_path / "phaladeepika"
    d.mkdir()
    (d / "ch08.json").write_text(json.dumps(doc), encoding="utf-8")
    with pytest.raises(PipelineError, match="failed verification"):
        run(DEMO, rules_dir=tmp_path, corpus_dir=CORPUS)


# --- condition evaluator ----------------------------------------------------

def _facts(*pairs):
    frame = {"reference": "lagna", "varga": "D1", "house_system": "whole_sign"}
    return FactSet([make_fact("in_house", {"graha": g, "house": h}, frame)
                    for g, h in pairs])


def test_evaluator_matches_and_reports_bindings():
    ev = evaluate({"all": [{"in_house": {"graha": "Sun", "house": 10}}]},
                  _facts(("Sun", 10)))
    assert ev.satisfied and ev.bindings == ("in_house(Sun,10)",)


def test_evaluator_does_not_confuse_adjacent_houses():
    ev = evaluate({"all": [{"in_house": {"graha": "Mars", "house": 7}}]},
                  _facts(("Mars", 8)))
    assert not ev.satisfied


def test_all_requires_every_condition():
    cond = {"all": [{"in_house": {"graha": "Sun", "house": 10}},
                    {"in_house": {"graha": "Moon", "house": 4}}]}
    assert not evaluate(cond, _facts(("Sun", 10))).satisfied
    assert evaluate(cond, _facts(("Sun", 10), ("Moon", 4))).satisfied


def test_unknown_predicate_is_inert_never_true():
    ev = evaluate({"all": [{"exalted": {"graha": "Sun"}}]}, _facts(("Sun", 10)))
    assert not ev.satisfied and ev.missing == ("exalted",)


# --- end to end -------------------------------------------------------------

def test_slice_runs_and_verifies():
    r = run(DEMO)
    assert r.verification.ok
    assert r.verification.checks["claims"] == 9        # one per body
    for k in ("quote_integrity_passed", "conditions_reevaluated_passed",
              "numeric_grounding_passed"):
        assert r.verification.checks[k] == 9


def test_every_claim_has_all_four_provenance_links():
    for c in run(DEMO).claims:
        assert c.astronomical["quantities"] and c.astronomical["bundle_id"]
        assert c.derived["rule_card"] and c.derived["conditions_satisfied"]
        assert c.source["book_title"] and c.source["chapter"]
        assert c.passage["quote"] and c.passage["char_span"] and c.passage["page_anchor"]


def test_every_sentence_is_sourced():
    r = run(DEMO)
    known = {c.claim_id for c in r.claims}
    assert r.sentences
    for s in r.sentences:
        assert s.claim_ids and set(s.claim_ids) <= known


def test_quoted_output_adds_no_words():
    """The Part 2 composer quotes; it must not paraphrase."""
    r = run(DEMO)
    by_id = {c.claim_id: c for c in r.claims}
    rules = [s for s in r.sentences if s.part == "rules"]
    assert len(rules) == 9
    for s in rules:
        assert s.text == by_id[s.claim_ids[0]].passage["quote_display"]


def test_coverage_reports_silence(provider):
    """A chart whose bodies have no cards must say so rather than invent."""
    chart = compute_chart(resolve_birth(DEMO, provider), provider)
    facts = extract_facts(chart)
    claims, report = activate(chart, facts, [], {})
    assert claims == [] and report["claims_activated"] == 0


def test_engine_names_no_book():
    """Extensibility guard (architecture 7.2).

    A book identifier anywhere in the engine means the corpus has leaked into
    the reasoning layer, and adding a book would then require an engine change.
    """
    banned = ("phaladeepika", "brihat-jataka", "mantreswara", "varahamihira")
    offenders = []
    for py in (ROOT / "Engine").rglob("*.py"):
        if "tests" in py.parts:
            continue
        low = py.read_text(encoding="utf-8").lower()
        for word in banned:
            if word in low:
                offenders.append(f"{py.relative_to(ROOT)}: {word}")
    assert not offenders, offenders


# --- the three-part consultation --------------------------------------------

def test_consultation_has_three_distinct_parts():
    text = run(DEMO).consultation
    for heading in ("## Part 1 — Objective chart facts",
                    "## Part 2 — Activated classical rules",
                    "## Part 3 — Synthesised interpretation"):
        assert heading in text, heading
    assert text.index("## Part 1") < text.index("## Part 2") < text.index("## Part 3")


def test_part_one_carries_no_citations():
    """Objective facts must not be mixed with doctrine."""
    text = run(DEMO).consultation
    part1 = text[text.index("## Part 1"):text.index("## Part 2")]
    assert "Phaladeepika" not in part1
    assert "PD.08" not in part1
    assert "printed p." not in part1


def test_part_two_cites_every_rule_to_the_page():
    r = run(DEMO)
    part2 = r.consultation[r.consultation.index("## Part 2"):
                           r.consultation.index("## Part 3")]
    for c in r.claims:
        assert c.claim_id in part2
        assert c.derived["rule_card"] in part2
        assert c.passage["page_anchor"] in part2
        assert c.passage["quote_display"] in part2


def test_part_three_cites_only_claims_from_part_two():
    r = run(DEMO)
    known = {c.claim_id for c in r.claims}
    synth = [s for s in r.sentences if s.part == "synthesis"]
    assert synth, "synthesis produced nothing"
    for s in synth:
        assert set(s.claim_ids) <= known


# --- synthesis --------------------------------------------------------------

def _claim(cid, house, quote):
    from Engine.activate import Claim
    return Claim(
        claim_id=cid,
        astronomical={"bundle_id": "x", "settings": {}, "backend": "", "quantities": []},
        derived={"facts": [{"key": f"in_house(Sun,{house})", "frame": {}, "evidence": {}}],
                 "rule_card": "X", "conditions_satisfied": [f"in_house(Sun,{house})"]},
        source={"book_id": "b", "book_title": "B", "author": "", "translator": "",
                "chapter": 1, "verse": "1", "tier": 1},
        passage={"quote": quote, "quote_display": quote, "corpus_file": "",
                 "char_span": [0, 1], "quote_sha256": "", "page_anchor": None,
                 "span_trimmed": None},
        weight=1.0, specificity=1, tier=1, stability="stable", text=quote,
    )


def test_synthesis_detects_a_contested_term():
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "The native will be wealthy and strong."),
              _claim("clm-2", 2, "The native will be devoid of wealth.")]
    themes = {t.term: t for t in synthesise(claims).themes}
    assert "wealth" in themes
    assert themes["wealth"].contested
    assert themes["wealth"].asserted == ("clm-1",)
    assert themes["wealth"].negated == ("clm-2",)


def test_synthesis_reads_destroy_as_negation():
    """Regression: 'He will destroy his wealth' once read as asserting wealth."""
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "The native will be wealthy and strong."),
              _claim("clm-2", 2, "He will destroy his wealth and take to bad conduct.")]
    themes = {t.term: t for t in synthesise(claims).themes}
    assert themes["wealth"].negated == ("clm-2",)


def test_synthesis_ignores_terms_in_a_single_passage():
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "The native will be wealthy."),
              _claim("clm-2", 2, "The native will be learned.")]
    assert synthesise(claims).themes == ()


def test_synthesis_ignores_scaffolding_words():
    from Engine.synthesis import synthesise
    claims = [_claim("clm-1", 1, "Saturn makes the native strong at birth."),
              _claim("clm-2", 2, "Jupiter makes the native bold at birth.")]
    assert [t.term for t in synthesise(claims).themes] == []


def test_synthesis_verifier_catches_a_word_not_in_the_passage():
    from Engine.synthesis import Occurrence, Theme, SynthesisResult, verify_synthesis
    claims = [_claim("clm-1", 1, "The native will be wealthy.")]
    bogus = SynthesisResult(
        concentrations=(),
        themes=(Theme("elephant", ("elephant",),
                      (Occurrence("clm-1", "elephant", False, None),)),),
        method_note="", total_claims=1,
    )
    problems = verify_synthesis(bogus, claims)
    assert any("not in clm-1" in p for p in problems)


def test_synthesis_concentration_matches_the_chart():
    r = run(DEMO)
    for con in r.synthesis.concentrations:
        occupants = [b.body for b in r.chart.bodies.values() if b.house == con.house]
        assert sorted(con.bodies) == sorted(occupants)
        assert len(con.claim_ids) > 1


def test_verification_records_synthesis_checks():
    r = run(DEMO)
    assert r.verification.checks["synthesis_grounded"] is True
    assert r.verification.checks["sentences_all_sourced"] == len(r.sentences)


# --- determinism -------------------------------------------------------------

def test_method_note_is_stable_across_processes():
    """Regression: the note sliced NEGATION_CUES (a frozenset) before sorting.

    Set iteration order for strings varies per process, so the same chart
    rendered a different method note on every run. An in-process check cannot
    catch this -- the hash seed is fixed for the life of the interpreter -- so
    each sample must be a separate subprocess.
    """
    import subprocess
    code = (
        "from Engine.synthesis import synthesise;"
        "print(synthesise([]).method_note)"
    )
    notes = {
        subprocess.run([sys.executable, "-c", code], cwd=ROOT,
                       capture_output=True, text=True, check=True).stdout
        for _ in range(4)
    }
    assert len(notes) == 1, f"method note varies between runs: {notes}"


def test_consultation_is_byte_identical_across_processes():
    """The whole report must be reproducible, not just the parts we thought of."""
    import subprocess
    code = (
        "from Engine.chart import BirthRecord;"
        "from Engine.pipeline import run;"
        "r = run(BirthRecord(date='1987-03-14', time='04:22',"
        "  timezone='Asia/Kolkata', latitude=10.7870, longitude=79.1378,"
        "  place_name='Thanjavur', time_precision='minute',"
        "  time_source='certificate'));"
        "import hashlib;"
        "print(hashlib.sha256(r.consultation.encode('utf-8')).hexdigest())"
    )
    digests = {
        subprocess.run([sys.executable, "-c", code], cwd=ROOT,
                       capture_output=True, text=True, check=True).stdout.strip()
        for _ in range(3)
    }
    assert len(digests) == 1, f"consultation is not reproducible: {digests}"
